# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprofile.proto\x12\x07profile\"9\n\x16RegisterProfileRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\x10RegisterResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32Z\n\x07Profile\x12O\n\x0fRegisterProfile\x12\x1f.profile.RegisterProfileRequest\x1a\x19.profile.RegisterResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profile_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERPROFILEREQUEST._serialized_start=26
  _REGISTERPROFILEREQUEST._serialized_end=83
  _REGISTERRESPONSE._serialized_start=85
  _REGISTERRESPONSE._serialized_end=135
  _PROFILE._serialized_start=137
  _PROFILE._serialized_end=227
# @@protoc_insertion_point(module_scope)
