# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fuser_auth.proto\x12\tuser_auth\"8\n\x15\x41uthenticationRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\":\n\x16\x41uthenticationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2e\n\x08UserAuth\x12Y\n\x10\x41uthenticateUser\x12 .user_auth.AuthenticationRequest\x1a!.user_auth.AuthenticationResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHENTICATIONREQUEST._serialized_start=30
  _AUTHENTICATIONREQUEST._serialized_end=86
  _AUTHENTICATIONRESPONSE._serialized_start=88
  _AUTHENTICATIONRESPONSE._serialized_end=146
  _USERAUTH._serialized_start=148
  _USERAUTH._serialized_end=249
# @@protoc_insertion_point(module_scope)
